version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - '1883:1883'
      - '9001:9001'
    security_opt:
      - no-new-privileges=true
    volumes:
      - ${PROJECT_DIR}/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ${PROJECT_DIR}/mosquitto/data:/mosquitto/data
      - ${PROJECT_DIR}/shared:/shared
