version: '3'

services:
  grafana:
    image: grafana/grafana-oss:9.2.5
    restart: unless-stopped
    depends_on:
      - influxdb
    env_file:
      - ${PROJECT_ROOT}/.docksal/etc/grafana/config/.env
    labels:
      - io.docksal.virtual-host=grafana.${VIRTUAL_HOST}
      - io.docksal.virtual-port=3000
    security_opt:
      - no-new-privileges=true
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/grafana/data:/var/lib/grafana

  influxdb:
    image: influxdb:2.5.1
    restart: unless-stopped
    env_file:
      - ${PROJECT_ROOT}/.docksal/etc/influxdb/config/.env
    labels:
      - io.docksal.virtual-host=influxdb.${VIRTUAL_HOST}
      - io.docksal.virtual-port=8086
    security_opt:
      - no-new-privileges=true
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/influxdb/data:/var/lib/influxdb2

  nodered:
    image: nodered/node-red:latest-18-minimal
    restart: unless-stopped
    env_file:
      - ${PROJECT_ROOT}/.docksal/etc/nodered/config/node-red.env
    environment:
      - TZ=${TZ}
    labels:
      - io.docksal.virtual-host=node-red.${VIRTUAL_HOST}
      - io.docksal.virtual-port=1880
    security_opt:
      - no-new-privileges=true
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/nodered/data:/data

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    security_opt:
      - no-new-privileges=true
    volumes:
      - ${PROJECT_ROOT}/.docksal/etc/timescaledb/data:/home/postgres/pgdata/data
