#!/usr/bin/env bash

## Run blt setup commands to prepare your local site for
## development.
##
## Usage: fin init

# Abort if anything fails
set -e
#-------------------------- Settings --------------------------------

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- END: Helper Functions --------------------------------

#-------------------------- Execution --------------------------------

cp $PROJECT_ROOT/.docksal/etc/grafana/config/.tpl.env $PROJECT_ROOT/.docksal/etc/grafana/config/.env
cp $PROJECT_ROOT/.docksal/etc/influxdb/config/.tpl.env $PROJECT_ROOT/.docksal/etc/influxdb/config/.env
fin config

# Initialize stack
fin reset -f

# Install project requirements
fin exec composer clear-cache --no-interaction
fin exec COMPOSER_PROCESS_TIMEOUT=2000
fin exec COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction

# Set up botc
cp $PROJECT_ROOT/htdocs/.env.example $PROJECT_ROOT/htdocs/.env
cp $PROJECT_ROOT/assets/settings.local.php $PROJECT_ROOT/htdocs/app/sites/default/settings.local.php
echo "2dSsqJleem3M3Fw" > ./htdocs/private/keys/influxdb.key.txt
fin drush si --existing-config -y
fin drush uli

echo
echo -en "${green_bg} DONE! ${NC}"
echo
echo -e "Open ${yellow}https://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
